/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pro
 */
public class register extends javax.swing.JPanel {

    /**
     * Creates new form register
     */
    public static Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
        
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_reg_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_reg_mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_reg_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_reg_password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_pass_color = new javax.swing.JComboBox<>();
        btn_register_submit = new javax.swing.JButton();
        txt_pass_color = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("Name");

        txt_reg_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reg_nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Mobile");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Register");

        jLabel4.setText("Email");

        txt_reg_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reg_emailActionPerformed(evt);
            }
        });

        jLabel5.setText("Password");

        jLabel6.setText("(Only 1-8 & a-h)");

        jLabel7.setText("Password Color");

        cmb_pass_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- No Color --", "Blue", "Yellow", "Orange", "Gray", "Red", "Pink", "Cyan", "Green" }));
        cmb_pass_color.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_pass_colorItemStateChanged(evt);
            }
        });
        cmb_pass_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pass_colorActionPerformed(evt);
            }
        });

        btn_register_submit.setBackground(new java.awt.Color(0, 204, 204));
        btn_register_submit.setForeground(new java.awt.Color(102, 102, 255));
        btn_register_submit.setText("Submit");
        btn_register_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_submitActionPerformed(evt);
            }
        });

        txt_pass_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pass_colorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_register_submit)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_reg_name, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(txt_reg_mobile)
                                            .addComponent(txt_reg_email))
                                        .addComponent(txt_reg_password, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cmb_pass_color, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_pass_color, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_reg_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_reg_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_reg_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txt_reg_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_pass_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_pass_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btn_register_submit)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>                        

    private void cmb_pass_colorActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txt_reg_nameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btn_register_submitActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        String name = txt_reg_name.getText();
        String mobile = txt_reg_mobile.getText();
        String email = txt_reg_email.getText();
        String password = txt_reg_password.getText();
        String color = cmb_pass_color.getSelectedItem().toString();
        
        if(name.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Name cannot be Empty"); 
           return;
        }
        
        if(mobile.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Mobile cannot be Empty"); 
           return;
        }
        if(email.equals(""))
        {
           JOptionPane.showMessageDialog(null, "EMail cannot be Empty"); 
           return;
        }
        if(password.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Password cannot be Empty"); 
           return;
        }
        if(cmb_pass_color.getSelectedIndex() == 0)
        {
           JOptionPane.showMessageDialog(null, "Please select your preffered color"); 
           return;
        }
        
        
        try
        {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:mydatabase.sqlite");
        }catch(ClassNotFoundException | SQLException | HeadlessException e)
        {    
            JOptionPane.showMessageDialog(null, e);
        }
        
        String sql;
        sql = "Insert into users (Name,Mobile,Email,Password,Color) values ('" +  name + "','" + mobile + "','" + email + "','" + password + "','" + color +  "')";
        
        try
        {
            //conn = Connect.ConnectDB();
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
        
            JOptionPane.showMessageDialog(null, "saved");
            conn.close();
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,"Sorry...! Duplicacy Not allowed");   
           
            
        }
    
    }                                                   

    private void txt_pass_colorActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void cmb_pass_colorItemStateChanged(java.awt.event.ItemEvent evt) {                                                
        // TODO add your handling code here:
        if(cmb_pass_color.getSelectedItem().equals("Blue"))
        {
            txt_pass_color.setBackground(Color.BLUE);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Yellow"))
        {
            txt_pass_color.setBackground(Color.YELLOW);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Orange"))
        {
            txt_pass_color.setBackground(Color.orange);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Gray"))
        {
            txt_pass_color.setBackground(Color.LIGHT_GRAY);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Red"))
        {
            txt_pass_color.setBackground(Color.RED);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Pink"))
        {
            txt_pass_color.setBackground(Color.PINK);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Cyan"))
        {
            txt_pass_color.setBackground(Color.cyan);
        }
        else if(cmb_pass_color.getSelectedItem().equals("Green"))
        {
            txt_pass_color.setBackground(Color.GREEN);
        }
    }                                               

    private void txt_reg_emailActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_register_submit;
    private javax.swing.JComboBox<String> cmb_pass_color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_pass_color;
    private javax.swing.JTextField txt_reg_email;
    private javax.swing.JTextField txt_reg_mobile;
    private javax.swing.JTextField txt_reg_name;
    private javax.swing.JTextField txt_reg_password;
    // End of variables declaration                   
}
